#!/bin/bash
# GitHub repository setup helper

echo "=== GitHub Repository Setup ==="
echo ""
echo "Option 1: Use gh CLI (recommended)"
echo "--------------------------------------"
echo "# Authenticate first:"
echo "gh auth login"
echo ""
echo "# Create repo:"
echo "gh repo create op-dbus --public --description 'Universal declarative system state management via native protocols' --source=. --remote=origin"
echo ""
echo "# Push code:"
echo "git push -u origin master"
echo ""
echo ""
echo "Option 2: Manual GitHub creation"
echo "--------------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: op-dbus"
echo "3. Description: Universal declarative system state management via native protocols"
echo "4. Public repository"
echo "5. Don't initialize with README (we have one)"
echo "6. Create repository"
echo ""
echo "Then run these commands:"
echo "git remote add origin https://github.com/YOUR-USERNAME/op-dbus.git"
echo "git branch -M master"
echo "git push -u origin master"
echo ""
echo ""
echo "Current git status:"
echo "-------------------"
git log --oneline -1
echo ""
echo "Ready to push!"
