#!/usr/bin/env bash

echo "=== OpenFlow JSON-RPC Examples ==="
echo "Use these curl commands to manage OpenFlow rules via JSON-RPC"
echo ""

echo "1. APPLY DEFAULT RULES:"
echo "curl -X POST http://localhost:8096/jsonrpc \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"openflow.apply_default_rules\","
echo "    \"params\": {\"bridge\": \"ovsbr0\"},"
echo "    \"id\": 1"
echo "  }'"
echo ""

echo "2. ADD CUSTOM RULE:"
echo "curl -X POST http://localhost:8096/jsonrpc \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"openflow.add_flow_rule\","
echo "    \"params\": {"
echo "      \"bridge\": \"ovsbr0\","
echo "      \"rule\": \"priority=200,tcp,tp_dst=80,actions=DROP\""
echo "    },"
echo "    \"id\": 2"
echo "  }'"
echo ""

echo "3. VIEW CURRENT RULES:"
echo "curl -X POST http://localhost:8096/jsonrpc \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"openflow.dump_flows\","
echo "    \"params\": {\"bridge\": \"ovsbr0\"},"
echo "    \"id\": 3"
echo "  }'"
echo ""

echo "4. CLEAR ALL RULES:"
echo "curl -X POST http://localhost:8096/jsonrpc \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"openflow.clear_flows\","
echo "    \"params\": {\"bridge\": \"ovsbr0\"},"
echo "    \"id\": 4"
echo "  }'"
echo ""

echo "5. APPLY TO ALL BRIDGES:"
echo "curl -X POST http://localhost:8096/jsonrpc \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"openflow.apply_all_default_rules\","
echo "    \"params\": {},"
echo "    \"id\": 5"
echo "  }'"
echo ""

echo "6. LIST AVAILABLE BRIDGES:"
echo "curl -X POST http://localhost:8096/jsonrpc \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"openflow.list_bridges\","
echo "    \"params\": {},"
echo "    \"id\": 6"
echo "  }'"
echo ""

echo "=== Notes ==="
echo "• Port 8096 is the dbus-mcp server (configured in dbus-orchestrator.nix)"
echo "• All ovs-ofctl commands are handled internally by the Rust D-Bus service"
echo "• No direct ovs-ofctl/ovs-vsctl commands are needed or allowed"
