#!/bin/bash
set -euo pipefail

# RustRover SSH Access Setup for Operation D-Bus
# This script configures SSH access for JetBrains RustRover IDE

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${0m} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${0m} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${0m} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${0m} $1"
}

check_ssh_server() {
    log_step "Checking SSH server status..."

    if ! systemctl is-active --quiet sshd 2>/dev/null && ! systemctl is-active --quiet ssh 2>/dev/null; then
        log_error "SSH server is not running"
        log_info "Start SSH server with: sudo systemctl start sshd"
        exit 1
    fi

    log_info "SSH server is running"
}

check_ssh_keys() {
    log_step "Checking SSH key configuration..."

    local ssh_dir="$HOME/.ssh"
    local key_file="$ssh_dir/id_rsa"
    local pub_key_file="$key_file.pub"
    local auth_keys_file="$ssh_dir/authorized_keys"

    # Check if SSH directory exists
    if [[ ! -d "$ssh_dir" ]]; then
        log_error "SSH directory not found: $ssh_dir"
        exit 1
    fi

    # Check if key pair exists
    if [[ ! -f "$key_file" ]] || [[ ! -f "$pub_key_file" ]]; then
        log_error "SSH key pair not found. Generate with: ssh-keygen -t rsa -b 4096"
        exit 1
    fi

    # Check if public key is in authorized_keys
    local pub_key
    pub_key=$(cat "$pub_key_file")
    if ! grep -q "$pub_key" "$auth_keys_file" 2>/dev/null; then
        log_warn "Public key not found in authorized_keys, adding it..."
        echo "$pub_key" >> "$auth_keys_file"
        chmod 600 "$auth_keys_file"
        log_info "Public key added to authorized_keys"
    fi

    log_info "SSH keys are properly configured"
}

check_directory_access() {
    log_step "Checking Operation D-Bus directory access..."

    local project_dir="/git/operation-dbus"

    if [[ ! -d "$project_dir" ]]; then
        log_error "Operation D-Bus directory not found: $project_dir"
        exit 1
    fi

    # Check if current user owns the directory
    local owner
    owner=$(stat -c '%U' "$project_dir")
    if [[ "$owner" != "$USER" ]]; then
        log_warn "Directory owned by $owner, not $USER"
        log_warn "Consider changing ownership: sudo chown -R $USER:$USER $project_dir"
    fi

    # Check permissions
    local perms
    perms=$(stat -c '%a' "$project_dir")
    if [[ "$perms" -lt 755 ]]; then
        log_warn "Directory permissions are restrictive: $perms"
        log_info "Fixing permissions: chmod 755 $project_dir"
        chmod 755 "$project_dir"
    fi

    log_info "Directory access is configured"
}

create_ssh_config() {
    log_step "Creating SSH configuration for RustRover..."

    local config_file="$HOME/.ssh/config_rustrover"
    local hostname
    hostname=$(hostname)
    local ip_address
    ip_address=$(hostname -I | awk '{print $1}')

    cat > "$config_file" << EOF
# RustRover SSH Configuration for Operation D-Bus
# Generated by setup-rustrover-ssh.sh on $(date)

# Operation D-Bus Development Server (by hostname)
Host operation-dbus
    HostName $hostname
    User $USER
    Port 22
    IdentityFile ~/.ssh/id_rsa
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile ~/.ssh/known_hosts_rustrover
    ServerAliveInterval 60
    ServerAliveCountMax 3
    ForwardAgent no
    ForwardX11 no

# Alternative connection using IP address
Host operation-dbus-ip
    HostName $ip_address
    User $USER
    Port 22
    IdentityFile ~/.ssh/id_rsa
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile ~/.ssh/known_hosts_rustrover
    ServerAliveInterval 60
    ServerAliveCountMax 3
    ForwardAgent no
    ForwardX11 no
EOF

    chmod 600 "$config_file"
    log_info "SSH configuration created: $config_file"
}

test_ssh_connection() {
    log_step "Testing SSH connection..."

    # Test local connection first
    if ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
           -i ~/.ssh/id_rsa "$USER@localhost" 'echo "SSH test successful"' 2>/dev/null; then
        log_info "SSH connection test passed"
    else
        log_error "SSH connection test failed"
        log_error "Check SSH server configuration and key permissions"
        exit 1
    fi
}

create_rustrover_instructions() {
    log_step "Creating RustRover setup instructions..."

    local instructions_file="$SCRIPT_DIR/RUSTROVER-SETUP.md"
    local hostname
    hostname=$(hostname)
    local ip_address
    ip_address=$(hostname -I | awk '{print $1}')

    cat > "$instructions_file" << EOF
# RustRover SSH Setup for Operation D-Bus

## Overview
This guide helps you configure JetBrains RustRover to connect to the Operation D-Bus development environment via SSH.

## Prerequisites
- RustRover IDE installed
- SSH access to the development server
- Operation D-Bus repository cloned

## SSH Configuration

### Option 1: Using Hostname (Recommended)
1. Open RustRover
2. Go to **File** → **Settings** → **Tools** → **SSH Configurations**
3. Click **+** to add a new configuration
4. Fill in the details:
   - **Host**: $hostname
   - **Port**: 22
   - **User name**: $USER
   - **Authentication type**: Key pair (OpenSSH or PuTTY)
   - **Private key file**: \`~/.ssh/id_rsa\` (or full path to your private key)
   - **Passphrase**: (leave empty if no passphrase)

### Option 2: Using IP Address
- **Host**: $ip_address
- **Port**: 22
- **User name**: $USER
- **Private key file**: \`~/.ssh/id_rsa\`

## Project Configuration

### Open Project via SSH
1. In RustRover, go to **File** → **Open**
2. Select **Remote Development**
3. Choose **SSH** as the connection type
4. Select your SSH configuration from the dropdown
5. Set the project path to: \`/git/operation-dbus\`
6. Click **Download and Open**

### Alternative: Clone via SSH
If you prefer to clone the repository:
\`\`\`bash
git clone ssh://$USER@$hostname/git/operation-dbus
\`\`\`

## Troubleshooting

### Connection Issues
- Verify SSH keys are properly configured
- Check that SSH server is running: \`sudo systemctl status sshd\`
- Test SSH connection manually: \`ssh $USER@$hostname\`

### Permission Issues
- Ensure you have read/write access to \`/git/operation-dbus\`
- Check file ownership: \`ls -la /git/operation-dbus\`

### Firewall Issues
- Ensure SSH port (22) is accessible
- Check firewall rules if applicable

## Development Workflow

1. **Connect**: Use RustRover's SSH remote development feature
2. **Code**: Edit files directly on the server
3. **Build**: Run builds remotely: \`cargo build --release\`
4. **Test**: Execute tests: \`cargo test\`
5. **Deploy**: Use the deployment scripts in \`deployment-repo/\`

## SSH Config File (Alternative)

If you prefer using an SSH config file, add this to \`~/.ssh/config\`:

\`\`\`
Host operation-dbus
    HostName $hostname
    User $USER
    Port 22
    IdentityFile ~/.ssh/id_rsa
    IdentitiesOnly yes
    StrictHostKeyChecking no
    ServerAliveInterval 60
    ServerAliveCountMax 3
\`\`\`

Then use **operation-dbus** as the host in RustRover.

## Security Notes

- SSH keys provide secure authentication
- No password authentication is used
- Connections are encrypted
- Consider using SSH agent forwarding if needed for Git operations

## Support

If you encounter issues:
1. Check the SSH server logs: \`sudo journalctl -u sshd\`
2. Verify key permissions: \`ls -la ~/.ssh/\`
3. Test manual SSH connection: \`ssh -v $USER@$hostname\`
EOF

    log_info "RustRover setup instructions created: $instructions_file"
}

main() {
    log_info "Setting up RustRover SSH access for Operation D-Bus..."

    check_ssh_server
    check_ssh_keys
    check_directory_access
    create_ssh_config
    test_ssh_connection
    create_rustrover_instructions

    log_info "✅ RustRover SSH setup complete!"
    echo
    log_info "Next steps:"
    echo "1. Review the setup instructions: ./RUSTROVER-SETUP.md"
    echo "2. Configure RustRover using the SSH settings above"
    echo "3. Connect to the project at: /git/operation-dbus"
    echo
    log_info "SSH Configuration Summary:"
    echo "  Host: $(hostname) or $(hostname -I | awk '{print $1}')"
    echo "  User: $USER"
    echo "  Port: 22"
    echo "  Key: ~/.ssh/id_rsa"
}

main "$@"