name: Sync to MCP Fork

on:
  push:
    branches: [main, master]
    paths:
      - 'src/mcp/**'
      - 'mcp-configs/**'
      - 'package.json'
      - 'mcp.json'
      - 'MCP-*.md'
      - 'docs/MCP-*.md'
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Add MCP fork remote
        run: |
          git remote add mcp-fork https://github.com/${{ secrets.MCP_FORK_REPO }}.git || true
          
      - name: Create MCP branch
        run: |
          git checkout -b mcp-sync-${{ github.sha }}
          
      - name: Filter MCP-related files
        run: |
          # Create a temporary directory for MCP files
          mkdir -p /tmp/mcp-export
          
          # Copy MCP-specific files
          cp -r src/mcp /tmp/mcp-export/src/
          cp -r mcp-configs /tmp/mcp-export/
          cp package.json /tmp/mcp-export/
          cp mcp.json /tmp/mcp-export/
          cp MCP-*.md /tmp/mcp-export/
          cp -r docs/MCP-*.md /tmp/mcp-export/docs/ 2>/dev/null || true
          
          # Copy the refactored modules
          mkdir -p /tmp/mcp-export/src/core
          cp -r src/plugin_system /tmp/mcp-export/src/core/ 2>/dev/null || true
          cp -r src/event_bus /tmp/mcp-export/src/core/ 2>/dev/null || true
          
      - name: Checkout MCP fork
        run: |
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ secrets.MCP_FORK_REPO }}.git /tmp/mcp-fork
          cd /tmp/mcp-fork
          git checkout main || git checkout master
          
      - name: Sync files
        run: |
          cd /tmp/mcp-fork
          
          # Copy updated files
          cp -r /tmp/mcp-export/* .
          
          # Add all changes
          git add -A
          
          # Check if there are changes
          if git diff --staged --quiet; then
            echo "No changes to sync"
            exit 0
          fi
          
          # Commit changes
          git commit -m "Sync from main repo: ${{ github.event.head_commit.message }}"
          
      - name: Push to MCP fork
        run: |
          cd /tmp/mcp-fork
          git push origin main || git push origin master
          
      - name: Create Pull Request
        if: ${{ github.event_name == 'push' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ secrets.MCP_FORK_REPO }}
          title: "[Auto] Sync from main repository"
          body: |
            ## Automated Sync
            
            This PR syncs changes from the main operation-dbus repository.
            
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            
            ### Changed files:
            ${{ steps.changed-files.outputs.all_modified_files }}
            
            ---
            *This is an automated sync. Please review before merging.*
          branch: sync-${{ github.sha }}
          base: main